export const ROUTES = {
  login: "/login",
  dashboard: "/dashboard",
  assessments: "/assessments",
  adminUsers: "/admin/users",
  projectWorkspace: "/workspace",
  repositories: "/repositories",
  repositoryOnboard: "/repositories/onboard",
  repository: "/repositories/:repoId",
  repositoryDetail: "/repositories/:repoId",
  assessmentBuild: "/repositories/:repoId/topics/:topicId/assessment/build",
  assessmentTake: "/assessment/:assessmentId/take",
  assessmentResults: "/assessment/:assessmentId/results",
  assessmentMyResult: "/assessment/:assessmentId/my-result",
  attemptDetail: "/assessment/attempts/:attemptId",
  project: "/project/:projectId",
  projectAssessment: "/project/:projectId/assessment",
} as const;
