"""add kt topic contributor assignment models

Revision ID: bb9f895432eb
Revises: add_user_name
Create Date: 2026-06-17 14:47:44.832406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9f895432eb'
down_revision: Union[str, None] = 'add_user_name'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('top_files', sa.String(length=2000), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributors_repository_id'), 'contributors', ['repository_id'], unique=False)
    op.create_table('kt_topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path_patterns', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kt_topics_repository_id'), 'kt_topics', ['repository_id'], unique=False)
    op.create_table('repository_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('kt_topic_id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kt_topic_id'], ['kt_topics.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kt_topic_id', 'learner_id', name='uq_topic_learner')
    )
    op.create_index(op.f('ix_repository_assignments_kt_topic_id'), 'repository_assignments', ['kt_topic_id'], unique=False)
    op.create_index(op.f('ix_repository_assignments_learner_id'), 'repository_assignments', ['learner_id'], unique=False)
    op.create_index(op.f('ix_repository_assignments_repository_id'), 'repository_assignments', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_assignments_repository_id'), table_name='repository_assignments')
    op.drop_index(op.f('ix_repository_assignments_learner_id'), table_name='repository_assignments')
    op.drop_index(op.f('ix_repository_assignments_kt_topic_id'), table_name='repository_assignments')
    op.drop_table('repository_assignments')
    op.drop_index(op.f('ix_kt_topics_repository_id'), table_name='kt_topics')
    op.drop_table('kt_topics')
    op.drop_index(op.f('ix_contributors_repository_id'), table_name='contributors')
    op.drop_table('contributors')
