"""add kt checklist models

Revision ID: ddf1bac62a9c
Revises: bb9f895432eb
Create Date: 2026-06-18 07:42:13.251126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf1bac62a9c'
down_revision: Union[str, None] = 'bb9f895432eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kt_checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kt_topic_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kt_topic_id'], ['kt_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kt_checklist_items_kt_topic_id'), 'kt_checklist_items', ['kt_topic_id'], unique=False)
    op.create_table('kt_checklist_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checklist_item_id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checklist_item_id'], ['kt_checklist_items.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_item_id', 'learner_id', name='uq_checklist_item_learner')
    )
    op.create_index(op.f('ix_kt_checklist_progress_checklist_item_id'), 'kt_checklist_progress', ['checklist_item_id'], unique=False)
    op.create_index(op.f('ix_kt_checklist_progress_learner_id'), 'kt_checklist_progress', ['learner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kt_checklist_progress_learner_id'), table_name='kt_checklist_progress')
    op.drop_index(op.f('ix_kt_checklist_progress_checklist_item_id'), table_name='kt_checklist_progress')
    op.drop_table('kt_checklist_progress')
    op.drop_index(op.f('ix_kt_checklist_items_kt_topic_id'), table_name='kt_checklist_items')
    op.drop_table('kt_checklist_items')
    # ### end Alembic commands ###
